apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-game-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 2048-game
  template:
    metadata:
      labels:
        app: 2048-game
    spec:
      containers:
      - name: 2048-game
        image: 2048-game:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: 2048-game-service
spec:
  selector:
    app: 2048-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
